name: Periodic Database Update

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout koda
      uses: actions/checkout@v3

    - name: Podešavanje Python-a
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Instalacija zavisnosti
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3 mtranslate

    - name: Pokretanje generate_db.py
      run: python generate_db.py

    - name: Pokretanje generate_interactions.py
      run: python generate_interactions.py

    - name: Commit i Push izmena
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        # Dodajemo sve izmene u .json fajlovima
        git add *.json
        # Pull sa rebase osigurava da GitHub Action spoji tvoje manuelne push-ove sa novog PC-a
        git pull --rebase origin main
        # Commit i push samo ako ima stvarnih promena
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Automatsko ažuriranje baze [skip ci]"
          git push origin main
        else
          echo "Nema promena za commit."
        fi