name: Periodic Database Update

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout koda
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Podešavanje Python-a
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Instalacija zavisnosti
      run: |
        python -m pip install --upgrade pip
        pip install requests urllib3 mtranslate

    - name: Pokretanje skripti
      run: |
        python generate_db.py
        python generate_interactions.py

    - name: Sacuvaj promene
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add *.json
        
        # Provera da li ima stvarnih promena
        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "Automatsko ažuriranje baze [skip ci]"
          # Pre nego što uradi push, još jednom povlači najnovije stanje (rebase) 
          # u slučaju da si ti nešto pushovao dok je skripta radila
          git pull --rebase origin main
          git push origin main
        else
          echo "Nema promena za commit."
        fi
